# Generated by Django 2.1.4 on 2018-12-10 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishName', models.CharField(max_length=191)),
                ('description', models.CharField(max_length=191)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Php amount')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=191)),
                ('street', models.CharField(max_length=191)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('stateOrProvince', models.CharField(max_length=191)),
                ('country', models.CharField(max_length=191)),
                ('telephone', models.CharField(max_length=191)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3, verbose_name='Rating (stars)')),
                ('comment', models.CharField(max_length=191)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='restaurants.Restaurant'),
        ),
        migrations.AddField(
            model_name='dish',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
