# Generated by Django 2.1.4 on 2018-12-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20181210_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='dishName',
            new_name='dish_name',
        ),
    ]
